apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "case1.fullname" . }}-tpl-config
  namespace: {{.Release.Namespace}}
data:
  testfiles1: |
  {{ tpl (.Files.Get "conf/app.conf") . | nindent 4 }}
