apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "case1.fullname" . }}-keep-config
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/resource-policy": keep
data:
  keepfile: |
    Alan來過這到此一遊
